### ISSUE TITLE
image cannot be parsed

### ISSUE THREAD

**Issue by GpuLover** [d3x-at/sd-parsers#3]
Hi,
this image failed to be parsed, prompt_data = parser_manager.parse(filename) returns None
I got the image from civitai.com, PNG info from automatic1111 can parse it.

Thanks.

![00031-3995568945](https://github.com/d3x-at/sd-parsers/assets/114974844/bb379378-a192-42c1-8471-d3c238cd5b77)

**Comment by GpuLover** [comment]
seems to be an issue in the split_meta method of the automatic1111.py module

I don't understand why it treats the last line as key:value separated by commas, since last line also contains the negative prompt (format change from automatic11111 maybe?)

**Comment by d3x-at** [comment]
This issue should now be fixed in the [dev0.3](https://github.com/d3x-at/sd-parsers/tree/dev0.3) branch, commit 432a437.
If you're feeling adventurous, feel free to `pip install --upgrade git+https://github.com/d3x-at/sd-parsers.git@dev0.3` to test it out.
Be aware, that 0.3 will be breaking existing code - check the examples for what's changed.

**Comment by GpuLover** [comment]
I don't think stable-diffusion-webui was used to generate the image, I don't know what he use, you can see other here : https://civitai.com/images/4033343

PNG ingo from stable-diffusion-webui also has troubles parsing the file, when you clic send it txt2img.

Thanks I will try the dev branch
